import 'package:shared/shared.dart';

abstract interface class IApiKeyAuthenticator {
  /// Authenticates the api key request and loads the corresponding key with its details.
  Future<IApiKey?> authenticate(String rawKey);

  /// Generates the key, which will be used as the API Key
  String generateRawApiKey();

  /// Hashes the api key generated by [generateRawApiKey].
  /// This hash value will be stored in the database and used to authenticate the api key request.
  String hashApiKey(String rawKey);
}
